### ISSUE TITLE
Handle non-finite floats

### ISSUE THREAD

**Issue by filmor** [Pyrlang/Term#7]
With erlport, I ran into the problem that the bare Python float can carry `inf` and `nan` values, while Erlang can't. `binary_to_term` will fail on decoding a float encoded like this:

     binary_to_term(<<131,70,127,248,0,0,0,0,0,0>>). # NEW_FLOAT_EXT encoded float("nan")

This is enforced here: https://github.com/erlang/otp/blob/d6285b0a347b9489ce939511ee9a979acd868f71/erts/emulator/sys/unix/erl_unix_sys.h#L361

For our use-case, I now convert `inf`, `nan` and `-inf` to atoms, though erroring here would also be fine, it just has to be done on the Python side.

**Comment by s2hc-johan** [comment]
Hi,

Since this is a low level lib I'm not that exciting in casting to atoms, since if you do a round trip from py to erl and back to py you would end up with different values, unless we hijack the 3 atoms, in case your're out of luck if you would use the atom inf and then end up with a float on the python side.

I'm working on moving the endoce hooks to be evalueated before the default conversion, that would give you the possibility to create an encode hook and then make a hook for float and make the conversion in any way you like.

if an encode hook is not fast enough we could possibly make an option like `'non_finit_floats_as_atom': True` or similar.

**Comment by filmor** [comment]
That all sounds good, but even in the case where none of this conversion happens, you should at least error out on the encoding site instead of having it fail when decoding things. I'm not quite sure how Erlang's distribution reacts to (slightly) broken ETF.
